### ISSUE TITLE
How to generate images

### ISSUE THREAD

**Issue by ljlljlljl-1972** [Chenzhaowei13/Light-Condition-Style-Transfer#1]
Hi,  I would like to know how to generate images in low light condition? 
Thank you!

**Comment by Chenzhaowei13** [comment]
> Hi, I would like to know how to generate images in low light condition?
> Thank you!
The  images in low-light conditions are generated by Better-CycleGAN. We will open the source code for Better-CycleGAN soon. You can use CycleGAN generate images for the moment.

**Comment by Chenzhaowei13** [comment]
> Hi, I would like to know how to generate images in low light condition?
> Thank you!

The images in low-light conditions are generated by Better-CycleGAN. We will open the source code for Better-CycleGAN soon. You can use CycleGAN generate images for the moment.
