### ISSUE TITLE
when will you release the source code of SIM-CycleGAN?

### ISSUE THREAD

**Issue by XuDongHecs** [Chenzhaowei13/Light-Condition-Style-Transfer#10]
<sub>Sent from <a href="https://apps.apple.com/cn/app/id1314212521">PPHub</a></sub>

**Comment by Chenzhaowei13** [comment]
Hi, source code of SIM-CycleGAN has been released. If thera are any questions, please contact me.

**Comment by Chenzhaowei13** [comment]
Hi, source code of SIM-CycleGAN has been released. If there are any questions, please contact me.

**Comment by SoulmateB** [comment]
Hi, thanks. Would you tell me the train data and test data about SIM-CycleGAN？And Is it possible to  provide the model？ Thanks！
