### ISSUE TITLE
Hi，Thank you for your work. When to open the source code for Better-CycleGAN？

### ISSUE THREAD

**Issue by xxzcpsmemeda** [Chenzhaowei13/Light-Condition-Style-Transfer#2]

**Comment by Chenzhaowei13** [comment]
Maybe a few weeks later.  If you get inerested of our work, you can try the trained model of lane detection. ( It gets 73.9 F1-measure in CULane testing set)

**Comment by xxzcpsmemeda** [comment]
Can you send me the file directory and semantic partition maps of Tusimple dataset?




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"MaybeShewill-CV"<notifications@github.com&gt;;
发送时间:&nbsp;2020年2月11日(星期二) 上午10:55
收件人:&nbsp;"Chenzhaowei13/Light-Condition-Style-Transfer"<Light-Condition-Style-Transfer@noreply.github.com&gt;;
抄送:&nbsp;"2627084603"<2627084603@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [Chenzhaowei13/Light-Condition-Style-Transfer] Hi，Thank you for your work. When to open the source code for Better-CycleGAN？ (#2)




Maybe a few weeks later.  If you get inerested of our work, you can try the trained model of lane detection. ( It gets 73.9 F1-measure in CULane testing set)

**Comment by xxzcpsmemeda** [comment]
期待您的开源



---Original---
