### ISSUE TITLE
demo.py argumenst

### ISSUE THREAD

**Issue by yassinekebbati** [Chenzhaowei13/Light-Condition-Style-Transfer#6]
Hello sir ! 
when i try to run the demo.py i get the following error

![Capture](https://user-images.githubusercontent.com/49916054/78413589-55437b80-7618-11ea-858d-b4f93f445de4.PNG)

there was no mention as to specifying these arguments !! could you please guide me on this thank you!

**Comment by Chenzhaowei13** [comment]
Hi!
You can try```sh ./demo.sh```.  The needed arguments have been written in sh file.
If you have any other questions you can continue to ask here.

**Comment by yassinekebbati** [comment]
Yes that solved the issue thank you!
