### ISSUE TITLE
SIM-CycleGAN

### ISSUE THREAD

**Issue by zhangxiaopang88** [Chenzhaowei13/Light-Condition-Style-Transfer#7]
您好，很高兴你能开源您的代码，我对 SIM-CycleGAN这部分比较感兴趣，请问大概什么适合能开源这部分的代码 @Chenzhaowei13

**Comment by Chenzhaowei13** [comment]
谢谢关注！疫情原因今年IV延期到十月底进行。我应该会在那之后抽时间整理相关代码。感谢理解！

**Comment by hedgehogzoey** [comment]
你好 可以问一下大佬 result部分 在table1 里面的crossroad 的那些数据代表什么呢？为什么SCNN的1990是最好的？

**Comment by Chenzhaowei13** [comment]
你好，crossroad 场景没有车道线，用FP衡量。
我的理解是模型召回结果越多，更容易出现误检，再加上生成数据噪点较多，也容易导致增加检测模型的误检。
